name: "defold-pbr-utils"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies for Linux
          run: sudo apt-get install -y libxi-dev libx11-dev libxcursor-dev libgl1-mesa-dev
        - name: Build PBR Utils for Linux
          run: ./build.sh
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-linux
            path: ./build/pbr-utils

    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build PBR Utils for windows
          run: ./build.sh
          shell: bash
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-windows
            path: |
              ./build/pbr-utils.exe
    build-macos:
      strategy:
        matrix:
          platform: [x86_64-macos, arm64-macos]
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build PBR Utils for macos
          run: ./build.sh
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-osx
            path: |
              ./build/pbr-utils-${{ matrix.platform }}
