name: "defold-pbr-utils"

on:
  push:
    branches:
      - '*'

jobs:
    build-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build PBR Utils for Linux
          run: ./build.sh
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-linux
            path: ./build/pbr-utils

    build-windows:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build PBR Utils for windows
          run: ./build.sh
          shell: bash
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-windows
            path: |
              ./build/pbr-utils.exe
    build-macos:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build PBR Utils for macos
          run: ./build.sh
        - name: Archive results
          uses: actions/upload-artifact@v3
          with:
            name: defold-pbr-utils-osx
            path: |
              ./build/pbr-utils
